apiVersion: v2
name: jenkins
description: An Umbrella Jenkins Helm chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: jenkins
  version: 5.8.7
  repository: https://charts.jenkins.io