# Definition of dependency on Chart.yaml
jenkins:
  # From official jenkins values.yaml
  persistence:
    size: "9Gi"
  controller:
    image:
        # -- Controller image registry
        registry: "docker.io"
        # -- Controller image repository
        repository: "jenkins/jenkins"
        tag: "2.479.1-jdk17"
    JCasC:
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to our CI\CD server. This Jenkins is configured and managed 'as code'.