# Definition of dependency on Chart.yaml
jenkins:
  # From official jenkins values.yaml
  controller:
    JCasc:
      configScripts:
        welcome-message: |
          jenkins:
            SystemMessage:  Welcome to our CI\CD server. This Jenkins is configured and managed 'as code'.