apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-prod
  namespace: argocd
spec:
  destination:
    namespace: jenkins-prod
    # TODO
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/jenkins-umbrella
    repoURL: https://github.com/vargat9705/jenkins-gitops-template.git
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true