apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    name: kind
  project: default
  source:
    path: charts/jenkins-umbrella
    # TODO
    repoURL: https://github.com/morey-tech/argo-cd-helm-values-demo
    # TODO
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true